// web/src/pages/SignUp/index.tsx
/* eslint-disable prettier/prettier */
import React, { useCallback } from 'react';
import { Form } from '@unform/web';
import {
  FiMail,
  FiLock,
  FiUser,
  FiChevronLeft,
} from 'react-icons/fi';
import signupBackground from '../../assets/signup.svg';
import {
  Background,
  Container,
  Content,
  Links,
} from './styles';

import Input from '../../components/Input';
import Button from '../../components/Button';

const SignUp: React.FC = () => {
  const handleSubmit = useCallback((data: object): void => {
    console.log(data);
  }, []);

  return (
    <Container>
      <Background>
        <img src={signupBackground} alt="bg" />
        <p>Sign up now and never miss a word</p>
      </Background>
      <Content>
        <Form onSubmit={handleSubmit}>
          <h1>Sign Up</h1>
          <Input name="name" icon={FiUser} type="text" placeholder="Name" />
          <Input name="email" icon={FiMail} type="email" placeholder="E-mail" />
          <Input name="password" icon={FiLock} type="password" placeholder="Password" />
          <Input name="confirmPassword" icon={FiLock} type="password" placeholder="Confirm Password" />
          <Button type="submit">Sign up</Button>
          <Links>
            <a href="/">
              <FiChevronLeft />
              SignIn page
            </a>
          </Links>
        </Form>
      </Content>
    </Container>
  );
};

export default SignUp;

// web/angular/src/app/user/pages/sign-up/sign-up.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';

@Component({
  selector: 'app-sign-up',
  templateUrl: './sign-up.component.html',
  styleUrls: ['./sign-up.component.scss'],
})
export class SignUpComponent implements OnInit {
  public form: FormGroup;

  constructor() {}

  ngOnInit(): void {}
}

<div class="container">
  <div class="background">
    <img src="assets/signup.svg" alt="bg" />
    <p>Sign up now and never miss a word</p>
  </div>
  <div class="content">
    <form >
      <h1>Sign Up</h1>
      <app-input icon="user" name="name" type="text" placeholder="Name"></app-input>
      <app-input icon="mail" name="email" type="email" placeholder="E-mail"></app-input>
      <app-input icon="lock" name="password" type="password" placeholder="Password"></app-input>
      <app-input icon="lock" name="confirmPassword" type="password" placeholder="Confirm Password"></app-input>
      <app-button type="submit">Sign up</app-button>
      <div class="links">
        <a [routerLink]="['/']">
          <i-feather name="chevron-left"></i-feather>
          SignIn page
        </a>
      </div>
    </form>
  </div>
</div>
