// web/angular/src/app/user/pages/sign-up/sign-up.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';

@Component({
  selector: 'app-sign-up',
  templateUrl: './sign-up.component.html',
  styleUrls: ['./sign-up.component.scss'],
})
export class SignUpComponent implements OnInit {
  public form: FormGroup;

  constructor() {}

  ngOnInit(): void {}
}

<div class="container">
  <div class="background">
    <img src="assets/signup.svg" alt="bg" />
    <p>Sign up now and never miss a word</p>
  </div>
  <div class="content">
    <form >
      <h1>Sign Up</h1>
      <app-input icon="user" name="name" type="text" placeholder="Name"></app-input>
      <app-input icon="mail" name="email" type="email" placeholder="E-mail"></app-input>
      <app-input icon="lock" name="password" type="password" placeholder="Password"></app-input>
      <app-input icon="lock" name="confirmPassword" type="password" placeholder="Confirm Password"></app-input>
      <app-button type="submit">Sign up</app-button>
      <div class="links">
        <a [routerLink]="['/']">
          <i-feather name="chevron-left"></i-feather>
          SignIn page
        </a>
      </div>
    </form>
  </div>
</div>

// web/react/src/pages/SignUp/index.tsx
/* eslint-disable object-curly-newline */
import React, { ReactElement, useCallback, useRef } from 'react';
import * as Yup from 'yup';
import { Form } from '@unform/web';
import { FormHandles } from '@unform/core';
import { Link, useHistory } from 'react-router-dom';
import { FiMail, FiLock, FiUser, FiChevronLeft } from 'react-icons/fi';
import { UserSignUp } from '../../types';
import { api, getValidationErrors } from '../../utils';
import { Input, Button } from '../../components';
import signupBackground from '../../assets/signup.svg';
import { Background, Container, Content, Links } from './styles';

export function SignUp(): ReactElement {
  const formRef = useRef<FormHandles>(null);
  const history = useHistory();

  const handleSubmit = useCallback(
    async (data: UserSignUp) => {
      try {
        formRef.current?.setErrors({});

        const schema = Yup.object({
          name: Yup.string().required('Name is required'),
          email: Yup.string().email('Type a valid email').required('E-mail is required'),
          password: Yup.string().required('Senha obrigatória').min(6, 'At least 6 digits'),
          confirmPassword: Yup.string().oneOf([Yup.ref('password'), undefined], 'Senhas devem ser iguais'),
        });

        await schema.validate(data, {
          abortEarly: false,
        });

        const { name, email, password } = data;

        await api.post('/user', {
          name,
          email,
          password,
        });

        history.push('/');
      } catch (error) {
        const errors = getValidationErrors(error);
        formRef.current?.setErrors(errors);
      }
    },
    [history],
  );

  return (
    <Container>
      <Background>
        <img src={signupBackground} alt='bg' />
        <p>Sign up now and never miss a word</p>
      </Background>
      <Content>
        <Form onSubmit={handleSubmit} ref={formRef}>
          <h1>Sign Up</h1>
          <Input name='name' icon={FiUser} type='text' placeholder='Name' />
          <Input name='email' icon={FiMail} type='email' placeholder='E-mail' />
          <Input name='password' icon={FiLock} type='password' placeholder='Password' />
          <Input name='confirmPassword' icon={FiLock} type='password' placeholder='Confirm Password' />
          <Button type='submit'>Sign up</Button>
          <Links>
            <Link to='/'>
              <FiChevronLeft />
              SignIn page
            </Link>
          </Links>
        </Form>
      </Content>
    </Container>
  );
}
